### ISSUE TITLE
Localization is not work

### ISSUE THREAD

**Issue by Meklon2007** [prolog/shadow-of-the-wyrm#16] opened 2021-03-18 15:11 UTC
Hello. I don't know about other languages, but for russian language it looks like localization (example - cyrillic symbols) won't work, because in the code exist condition `c < 0`:
```
void SDLRender::render_text(....)
{
  char display_c = c;

  // Look up the letter
  if (c < 0 || c > display_params.get_num_glyphs())
  {
    display_c = '?';
  }
```
This is example russian 1251 font:
![ExportedFont](https://user-images.githubusercontent.com/12417354/111646836-0d126e80-8813-11eb-94fb-610b84c913ae.PNG)

But all russian letter showing as '?', because the ASCII code in char below zero (need unsigned char):

If text in win1251 and using bitmap font in example, the code must be something like:
```
(c<0 && (unsigned char)c>=0xC0 && (unsigned char)c <= 0xDF) - big russian letter in example font (win1251)
(c<0 && (unsigned char)c>=0xE0 && (unsigned char)c <= 0xFF) - small russian letter in example font (win1251)
```

**Comment by prolog** [comment] 2021-03-18 17:04
Thanks for reporting this! I didn't realize people were playing in Russian (haven't had an official version/translation in years). I can reproduce the issue and will have this fixed in the next version. I'll work on a fix later tonight.

**Closed** 2021-03-18 22:38 UTC

**Comment by prolog** [comment] 2021-03-18 22:40
I've checked in a fix to my develop branch. Please let me know if you'd e.g. like a snapshot build of v1.3.0 to test against.

**Comment by Meklon2007** [comment] 2021-03-18 23:03
Thanks. I just combined the Russian (from 0.5.1) and English files, and added something quite a bit. On older versions, it worked, then stopped. Yes, I could check if there would be a binary, I don't have all the required libraries to compile, just mingw.

**Comment by prolog** [comment] 2021-03-18 23:11
[ShadowOfTheWyrm-Win-1.3.0-charfix.zip](https://github.com/prolog/shadow-of-the-wyrm/files/6167643/ShadowOfTheWyrm-Win-1.3.0-charfix.zip)
Give this build a try. There was another small tweak that needed to be made to the code, but I tested it using an existing font and using high ASCII characters, and it was able to display them correctly.

**Comment by prolog** [comment] 2021-03-19 12:08
Back in 2016 a Russian player helped me release a full Russian curses version. He ran into the same issue, and determined it was an issue with a particular function in pdcurses. His solution was to update pdcurses. His explanation:

"I'll explain you how exactly I have modified pdcurses. Pdcurses (by default) forcibly replaces all output symbols to standart ASCII table. That's why all symbols different from latin cannot be displayed. In file addstr.c (pdcurses source file), in function "int waddnstr(WINDOW *win, const char *str, int n)" I replace call "waddch" on "waddrawch"."

If you wanted to play in curses mode, you could try:

1. Get the version of pdcurses.dll from the old Russian version I released, at https://www.shadowofthewyrm.org/releases/ru/ShadowOfTheWyrm_0.5.1_rus.zip
2. Replace the pdcurses.dll in your newer version of SotW with that one
3. Run cmd.exe
4. Type "chcp 1251"
5. CD to directory with game
6. Run sotw.exe.

It's been years since I've tested this out, but I was able to play the old Russian version of 0.5.1 this way and see Cyrillic text in curses. But if you're happy with the updates to 1.3.0, that's great too, and I'll include those in the next release.

**Comment by Meklon2007** [comment] 2021-03-19 12:24
yes, and this problem was solved. Russian is now displayed in all modes. Thanks.
